
apiVersion: v1
kind: Pod
metadata:
  name: todo
  labels:
    app: todoapp
spec:
  containers:
  - name: todo-frontend
    image: jqayyum/todo-frontend
    ports:
    - containerPort: 4200
  - name: todo-backend
    image: jqayyum/todo-backend
    ports:
    - containerPort: 8080
    